### ISSUE TITLE
Cuadro comparativo Diferentes textos Kevin  1"BS"

### ISSUE THREAD

**Issue by KevinOsorio23143** [SistemasTecTlaxiaco/actividad-5-cuadro-comparativo-de-textos-KevinOsorio23143#1]
[Cuadro comparativo Kevin Osorio.pdf](https://github.com/SistemasTecTlaxiaco/actividad-5-cuadro-comparativo-de-textos-KevinOsorio23143/files/9638981/Cuadro.comparativo.Kevin.Osorio.pdf)

**Comment by Daniel-Velasco-Lopez** [comment]
De la actividad 5
Obtuviste un 16.3% de los 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
